revoltchat/revite

- src/components/common/messaging/attachments/Grid.tsx
> Improve image embed scaling.

- src/components/common/messaging/MessageBase.tsx
- src/components/common/messaging/SystemMessage.tsx
This adds a basic implementation of system message icons, as per #10.
> Add system message icons. Closes #10

- src/context/intermediate/popovers/UserProfile.module.scss
fixed the border radius on profile preview popover
> feat:: updating border radius

- src/pages/settings/panes/Appearance.tsx
- src/pages/settings/panes/Panes.module.scss
https://github.com/revoltchat/revite/issues/73
> Fixed appearance tab text

- src/components/navigation/left/ServerListSidebar.tsx
https://github.com/revoltchat/revite/issues/68
> Add pings counter to server list

- src/context/intermediate/Intermediate.tsx
- src/context/intermediate/modals/Prompt.tsx
- src/lib/ContextMenus.tsx
**Note before merge**
There needs to be a translation created in the language repo
app.context_menu.create_category
> Added create category context menu when right clicking in channel list

- src/components/common/messaging/bars/ReplyBar.tsx
- src/lib/ContextMenus.tsx
Hides the mention button and disables the reply treating as a mention if it's from the currently signed in user
> Disable mentions on self-replies

- src/pages/settings/panes/Appearance.tsx
https://github.com/revoltchat/revite/issues/88
> Transparent will now fallback to the contrasting colour of background

- src/redux/reducers/experiments.ts
This Pull Request removes Search from experiments because its available now for everyone.
> Remove Search from experiments

- src/pages/settings/server/Overview.tsx
https://github.com/revoltchat/delta/issues/54
> Only display TextChannels as option for SystemMessage channels

- src/components/common/messaging/embed/Embed.tsx
closes https://github.com/revoltchat/delta/issues/61
The api types will also need to be updated but thats on gitlab still
> color -> colour

- src/pages/login/forms/MailProvider.tsx
Adds more provider domains, You could also add search params to some (i.e. `https://mail.google.com/#search/noreply%40steampowered.com`) but not sure what I should put in the search.
> Update Mail Providers

- src/pages/login/forms/FormLogin.tsx
prettier fixed formatting also ^
> Rename "ios" & "fxios" to "Safari" and "Firefox" for browser name

- .vscode/settings.json
- src/components/ui/Checkbox.tsx
- src/context/intermediate/Intermediate.tsx
- src/context/intermediate/Modals.tsx
- src/context/intermediate/Popovers.tsx
- src/context/intermediate/modals/TokenReveal.tsx
- src/context/intermediate/popovers/CreateBot.tsx
- src/pages/login/FormField.tsx
- src/pages/settings/panes/MyBots.tsx
- src/pages/settings/panes/Panes.module.scss
> Revamp "My Bots" page

- src/sw.ts
client side for https://github.com/revoltchat/delta/pull/72/files
> Parse Web Push notifications

- .github/workflows/docker.yml
* add test job
* add github container registry 
* refactor!
---
https://github.com/KeepSOBP/revite/actions/runs/1192566391
https://github.com/KeepSOBP/revite/actions/runs/1192568662
> Support multiple architectures for docker

- src/pages/settings/panes/MyBots.tsx
- src/pages/settings/panes/Panes.module.scss
Adds a dropdown for profile editing
> Add banner and info box to bots page

- src/components/navigation/LeftSidebar.tsx
- src/pages/channels/Channel.tsx
- src/pages/channels/ChannelHeader.tsx
- src/pages/home/Home.tsx
Add ability to hide the channel sidebar by clicking on the icons for the channel.
Also works for the home icon.
> Add ability to hide the channel sidebar

- src/context/Locale.tsx
As title says, changing the display for Japanese from saying Japan (the place) in Japanese to saying Japanese
> Update Locale.tsx language selection from Japan -> Japanese

- src/context/intermediate/popovers/ServerIdentityModal.module.scss
- src/context/intermediate/popovers/ServerIdentityModal.tsx
closes #56
Translations: https://github.com/revoltchat/translations/pull/1
> Revamp Server Identity Popover

- src/components/common/messaging/embed/EmbedInvite.tsx
> Format member count in invites

- src/components/navigation/left/ServerListSidebar.tsx
> Fix ping count alignment in Firefox

- src/context/Theme.tsx
- src/env.d.ts
- src/pages/settings/Settings.tsx
- src/pages/settings/assets/preview.svg
- src/pages/settings/panes/Appearance.tsx
- src/pages/settings/panes/Experiments.tsx
- src/pages/settings/panes/ThemeShop.tsx
- src/redux/reducers/experiments.ts
This pull request will remain a draft until translation keys are added, and an official default source for themes is chosen. 
The UI/UX needs work too, but that can be added later.
> Theme Shop

- src/components/common/messaging/Message.tsx
- src/components/common/user/UserShort.tsx
- src/components/markdown/Renderer.tsx
- src/components/navigation/left/ServerSidebar.tsx
- src/components/navigation/right/MemberList.tsx
- src/lib/ConditionalLink.tsx
- src/lib/links.ts
`shift+click` to mention users from the members sidebar, mentions, usernames, and avatars
`shift+click` to link to channels from the sidebar and channel links
This would finish https://github.com/revoltchat/revolt/discussions/84
> `shift+click` to mention or link to users and channels

- src/context/intermediate/popovers/ServerIdentityModal.tsx
- src/context/revoltjs/FileUploads.module.scss
- src/context/revoltjs/FileUploads.tsx
- server identity avatar preview now displays your current avatar, but desaturated and grayscale when no avatar is set
resolves #218
> Improve server identity avatar preview

- src/pages/RevoltApp.tsx
- src/pages/channels/Channel.tsx
This PR adds an informational screen for the case that there are no channels in a server, or in the future, if the user does not have the permission to see any channels.
It's marked as a draft as it depends on new strings from https://github.com/revoltchat/translations/pull/7.
> Placeholder for empty/failing servers

- src/context/Theme.tsx
- src/pages/settings/panes/Appearance.tsx
- src/pages/settings/panes/ThemeShop.tsx
- src/redux/index.ts
- src/redux/reducers/index.ts
- src/redux/reducers/themes.ts
- [#217] fixed theme shop themes not applying as a base
- added `themes` state path to store themes locally at
> Fix theme shop themes not applying as a base

- src/components/common/messaging/MessageBox.tsx
Fixes #239, #153, #261, and should fix #164.
However I was unable to reproduce #164 unlike the others.
> Fix enter key sending message while still composing

- src/context/intermediate/modals/Onboarding.tsx
- src/pages/channels/messaging/ConversationStart.tsx
Relies on https://github.com/revoltchat/translations/pull/12.
Changes the start of conversation text for saved notes.
> ConversationStart changed for notes/normal channel

- src/context/revoltjs/FileUploads.tsx
> Fix background not updating on profile

- src/pages/login/forms/MailProvider.tsx
> Fix iCluod mail address

- package.json
- src/components/common/messaging/MessageBox.tsx
- src/components/ui/SaveStatus.tsx
- src/context/intermediate/Intermediate.tsx
- src/context/intermediate/modals/Prompt.tsx
- src/lib/debounce.ts
- src/lib/dnd.ts
- src/pages/settings/ServerSettings.tsx
- src/pages/settings/server/Categories.tsx
- yarn.lock
> Implement Kanban-style category organisation.

- package.json
- src/context/Theme.tsx
- src/pages/channels/Channel.tsx
- src/pages/settings/channel/Overview.tsx
Add NSFW Switch to channel settings overview.
requires following PRs:
[Revolt.js#15](https://github.com/revoltchat/revolt.js/pull/15)
[Delta#90](https://github.com/revoltchat/delta/pull/90)
This also adds JetBrains Mono ([License](https://github.com/JetBrains/JetBrainsMono/blob/master/OFL.txt)) which was requested by users
Preview:
https://user-images.githubusercontent.com/8841466/133856712-83d1de2a-e895-4473-aa09-4f2759e52dee.mp4
> feat: handle nsfw flag & added monospace font

- src/components/common/ServerHeader.tsx
- src/pages/home/Home.tsx
(this requires revoltchat/translations#9 and replaces #243)
> feat(i18n): translate home buttons and server tooltips

- src/pages/settings/panes/Account.tsx
Closes #274.
This PR censors the whole email like this.
> fix: censor the whole email

- src/components/common/messaging/attachments/MessageReply.tsx
- src/pages/home/Home.module.scss
- src/pages/home/Home.tsx
- src/pages/home/snow.scss
- src/pages/settings/panes/Panes.module.scss
- src/pages/settings/panes/Profile.tsx
- src/pages/settings/panes/Sessions.tsx
- src/pages/settings/panes/ThemeShop.tsx
* new home screen
* cleaned up settings
> fix(home,settings): updated homepage, settings

- src/context/intermediate/popovers/UserProfile.tsx
> feat(UserProfile): add button to cancel outgoing friend request

- src/context/intermediate/modals/Prompt.tsx
Closes https://github.com/revoltchat/revite/issues/447
> fix: App soft crash when deleting servers

- .github/pull_request_template.md
Attempt 2 of #490  - this time based on master.
> chore(project management): Pull Request Template

- src/components/common/messaging/Message.tsx
- src/components/common/messaging/MessageBase.tsx
- src/components/common/messaging/bars/MessageOverlayBar.tsx
- src/styles/_elements.scss
* [n/a] (optional) I have opened a pull request on [the translation repository](https://github.com/revoltchat/translations)
Also added the boxicons' style for the reply button:
> feat(messaging): quick action bar

- src/components/common/messaging/MessageBase.tsx
> fix(components): convert .systemIcon to non-clickable

- src/context/Locale.tsx
* N/A (optional) I have opened a pull request on [the translation repository](https://github.com/revoltchat/translations)
> feat: add Latvian to the language list

- package.json
This PR ensures that Corepack users will use the right Yarn version.
> chore: specify yarn 1 for corepack

- src/components/common/messaging/MessageBox.tsx
Closes #332
Now, if the cursor is placed within a code block, `Enter` will not send a message, but rather insert a newline. You can still force-send with `Ctrl + Enter`
> feat: prevent accidental send while in code block

- src/pages/channels/voice/VoiceHeader.tsx
> fix(voice channel): Fix overflow and scrolling

- src/pages/login/forms/Form.tsx
https://user-images.githubusercontent.com/98860311/161637465-a5424cee-1399-4e92-a9e9-baf2c45c14c4.mp4
> fix(login): Fix render of welcome and subtitle text per page

- src/pages/settings/Settings.module.scss
Just getting used to git n' stuff so thought I would make an incredibly simple pull request fixing a very minor issue:
(streamable link because Github doesn't support webm and converting it doesn't work weeeee) https://streamable.com/i3fwzk
> fix: Bottom padding in settings

- src/lib/vortex/VoiceClient.ts
> feat: add sounds when user joins/leaves call

- src/components/settings/roles/PermissionList.tsx
- src/pages/settings/channel/Permissions.tsx
> fix: permission lists show wrong permissions

- src/components/common/messaging/attachments/AttachmentActions.tsx
- src/lib/ContextMenus.tsx
> fix: don't open new tab to download attachment

- package.json
- yarn.lock
> revert: "chore(deps-dev): bump prismjs from 1.24.1 to 1.27.0"

- src/pages/login/forms/Form.tsx
Adds this if Revite is connecting to somewhere other than api.revolt.chat:
Translation PR soon:tm:
(Looks like prettier changed other parts of the file as well)
> feat: add warning on self-hosted instances

- src/pages/invite/Invite.module.scss
Before:
Light Theme
Dark Theme
After:
Light Theme
Dark Theme
Closes #335
> fix: bug in join server button when in light theme

- src/components/navigation/BottomNavigation.tsx
> fix: bottom nav alignment is wrong

- src/context/intermediate/popovers/CreateBot.tsx
- src/context/intermediate/popovers/ModifyAccount.tsx
Fixes #696 
Read more https://github.com/revoltchat/revite/issues/696#issuecomment-1158452297
> fix: modify account, and create bot forms not being submitted

- src/components/settings/roles/PermissionSelect.tsx
- src/lib/ErrorBoundary.tsx
- src/pages/developer/Developer.tsx
> fix: styling fixes

- src/components/common/messaging/bars/TypingIndicator.tsx
Fixes #64 
Before:
After:
if there's no server identity(nickname or avatar) set, it uses user's global name and avatar.
> fix: display server identity (if present) in typing indicator

- src/controllers/modals/components/CreateInvite.tsx
https://user-images.githubusercontent.com/74418041/190865695-fd47bfa3-2242-4414-8141-cc7c1ff92bf1.mp4
> Use rvlt.gg instead of app.revolt.chat/invite for invites

- src/pages/home/Home.tsx
This PR just adds Halloween emojis using the code for the Christmas snowflakes in October.
Screenshots:
> feat: add seasonal halloween theme

- src/components/common/messaging/bars/TypingIndicator.tsx
> revert: "fix: display server identity (if present) in typing indicator"

- Dockerfile
- src/components/common/messaging/MessageBox.tsx
- src/mobx/stores/Draft.ts
- src/pages/home/Home.tsx
In relation to issue #825 
Things that have been fixed;
- The `checkout` task under the `test` step in the `docker` workflow fails due to missing submodules in `.gitmodules`.
- Fixed with `git rm --cache` on the "missing" submodules
- Type mismatches in relation to `DraftObject`
- Fixed by properly implementing `DraftObject` where it's used.
- `yarn build:deps` must be ran before `yarn typecheck` in `/Dockerfile`
> Fix CI/CD failure(s)

- src/lib/links.ts
> feat: allow rolt.chat for relative navigation

- src/mobx/stores/Draft.ts
* ~~(optional) I have opened a pull request on [the translation repository](https://github.com/revoltchat/translations)~~ N/A
* ~~I have included screenshots to demonstrate my changes~~ N/A
> fix: update draft check

- src/pages/settings/server/Roles.tsx
> fix(ui): add margin to delete role button

- src/pages/channels/voice/VoiceHeader.tsx
Fixes issues introduced in #574
> fix: overflow management in voice menus

- src/components/settings/account/AccountManagement.tsx
this will also require the languages submodules to be bumped
> feat: translate account management options

- tsconfig.json
> chore: resolve ts-to-JSX type hints

- src/lib/ContextMenus.tsx
> feat: admin panel link for system message user

- src/controllers/modals/components/ServerInfo.tsx
> fix: Add ability to leave server through server info screen

- src/components/common/messaging/MessageBox.tsx
https://github.com/user-attachments/assets/4765561b-d247-49f0-916d-ebfe84071aae
> fix: appending mention to draft content

- .env
- src/controllers/modals/components/ServerInfo.tsx
Fixes #1069 which was introduced in #1035
> fix: remove ability for owners to leave server from ServerInfo modal
