- src/components/common/messaging/MessageBox.tsx
For example, if a user types `s/abc/def` and their last message is `abcdefghij`, that message will be edited to `defdefghij`.
[Video link because GitHub doesn't let me upload the video directly and ffmpeg refuses to convert it](https://fuckthefren.ch/sc/1628804103-Peek%202021-08-12%2023-32.webm)
> Add sed replacement in message box

- src/components/common/messaging/attachments/Attachment.module.scss
- src/components/common/messaging/attachments/Attachment.tsx
- src/components/common/messaging/attachments/ImageFile.tsx
This PR adds a simple background to image attachments that have not been loaded.
As of writing, this PR feels hacky at best. I'm looking for some guidance, as well as permission to make image files its own component (just like how [text files have their own component](https://github.com/revoltchat/revite/blob/master/src/components/common/messaging/attachments/TextFile.tsx)).
Demonstration:
https://user-images.githubusercontent.com/39029839/129476409-496cfef5-9738-4c90-a7a2-28ef83102fe0.mp4
> Add background for loading image attachments

- src/pages/channels/messaging/MessageEditor.tsx
Editing message this way feels less crowded when editing large messages.
> Bump message editor rows to 10

- src/components/common/ChannelIcon.tsx
- src/components/common/IconBase.tsx
- src/components/common/ServerIcon.tsx
- src/components/common/user/UserIcon.tsx
- src/styles/_variables.scss
I personally like profile pictures to be less round, so I use a custom theme.
But currently with updates the CSS selectors get scrambled, which is quite annoying for the theming.
The other issue is `--border-radius-half` is very broad, changing it in the them could introduce unwanted side effects (square close button, etc)
My solution is to introduce 2 new CSS variables `--border-radius-user-profile-picture` and `--border-radius-server-icon`, by defaulted to `var(--border-radius-half)`.
Implementation-wise this translates into removing the square modifier for a more broad borderRadius modified, which can be null/undefined to reproduce the square modifier behavior, or be the value of the wanted CSS variable.
Hope this is reasonable!
> Introduce new border radius variables for stable theming.

- src/pages/invite/Invite.tsx
- Make it look similar to a valid invite page.
- Add back button which brings you to the home screen.
Fixes #157 
Only issue is the `background-url` is copied from the Testers invite page and this doesn't use i18n translations.
> Clean up invalid invite page.

- src/components/markdown/Renderer.tsx
- src/context/intermediate/modals/ExternalLinkPrompt.tsx
- src/redux/index.ts
- src/redux/reducers/index.ts
- src/redux/reducers/trusted_links.ts
Stores trusted domains in state after trusting.
> Add trusted domains in external link prompt

- src/pages/settings/panes/Panes.module.scss
Before: 
After:
(I'm not dead-set on 30px, but I think it gives enough space for the preview to not blend in with the lower text.)
> increase padding for profile preview

- src/components/common/messaging/attachments/Attachment.tsx
- src/components/common/messaging/attachments/Grid.tsx
- src/components/common/messaging/attachments/ImageFile.tsx
- fixed major bugs for chrome 93+ at the cost of minor issues that may appear (unsure, did not find any in testing)
- position scaled image to the left for firefox (firefox aspect-ratio still does not scale correctly)
- added `--width` and `--height` to the `Grid` for theme creators who may want to use such information easily
This may need more testing, only chrome 93 and firefox 91 were tested.
> Fix major image bugs for chrome 93+

- src/components/common/ServerHeader.tsx
- src/components/navigation/left/ServerSidebar.tsx
This PR adapts behaviour as such that:
* When joining a server, the first channel in the server is shown
* When deleting a channel, the first channel in the server is shown
* When opening a server on a new client for the first time, a the first channel in the server is shown
* Preserve the sidebar if no channels are available, to allow for creating a new channel (should deleting the last channel in the server be allowed at all?)
> Choose the first channel in the server if none is selected

- src/pages/settings/panes/Panes.module.scss
- src/styles/_variables.scss
The `.code` section under Theme Overrides in the Appearance settings uses the `--codeblock-font` variable, set to `"Fira Code"` and doesn't update to match the user's preferred monospace font (`--monospace-font`), making it inconsistent with the rest of the webapp (this was the only place the variable was used).
This creates issues when the user does not have Fira Code installed on their system and chooses a different monospace font, as it falls back to the browser default font (usually a serif font). See the screenshot below.
This PR removes the variable and uses `--monospace-font` to match the rest of the site.
> Use preferred monospace font for Theme Overrides code section

- src/pages/settings/panes/MyBots.tsx
(relies on revoltchat/translations#4)
> add tooltip/help icon for bot id

- src/context/intermediate/popovers/CreateBot.tsx
`app.special.popovers.create_bot.error` -> `app.special.popovers.create_bot.failed`
> Fix translation string in Create Bot popover

- src/pages/RevoltApp.tsx
- src/pages/invite/Invite.tsx
This fixes an issue wherein empty invites are not being treated as invalid and users are stuck without a left navigation panel due to invites counting as "special" routes.
Behaviour is adjusted to redirect to the homepage when an empty invite is provided.
> Redirect to home for empty invites

- src/redux/reducers/locale.ts
This prevents the language being automatically set to "enchantment" for English locales due to the string comparison being done with `startsWith`.
> Filter "alt" languages when selecting based on navigator

- src/components/ui/Category.tsx
This change aligns the category titles in settings visually with the icons, which looks a bit more pleasant IMO.
Before | After
--- | ---
Also works on mobile:
Before | After
--- | ---
> Add padding to settings category titles to align the visually with icons

- src/components/common/messaging/embed/EmbedMedia.tsx
This is a companion PR to https://github.com/revoltchat/january/pull/11.
It directly depends on https://github.com/revoltchat/api/pull/2. I wasn't sure on how to handle revolt-api changes in relation to revite, please let me know if there's anything else I have to do.
> Append youtube timestamp to embed url if provided by january

- src/pages/settings/panes/Audio.tsx
- ask user for microphone permission (prompt).
- handle error when permission is blocked.
- Suggest retry if the permission is still not set and no prompt.
> [settings][audio] fix labels of microphone selection

- .github/workflows/preview_cleanup.yml
- .github/workflows/preview_pull_request.yml
- src/context/index.tsx
- src/env.d.ts
Previews pull requests that have the `use-preview` labels attached to them by using github pages.
[Example pull request](https://github.com/brecert/revite/pull/3)
The workflow may need to be tweaked once added to this repository.
> Previews for pull requests

- src/components/common/messaging/bars/ReplyBar.tsx
- [#220] reply mention now uses translations
- reply mention styling improved
- `@` fits better
- `min-width: 6ch` is used to remove shifting between `on` and `off` lengths, mostly for the english `on/off` but could be modified to work with any language in the future.
Before: 
After:
> Improve reply mention styling

- src/components/navigation/left/ServerListSidebar.tsx
This attribute isn't transformed into kebab-case due to a bug in Preact.
> FIx ping counter alignment in Firefox but actually

- .github/actions/build/action.yml
- .github/workflows/docker.yml
- .github/workflows/mirroring.yml
- .github/workflows/preview_cleanup.yml
- .github/workflows/preview_pull_request.yml
This cleans up the code of the actions, improves the safety of them, overall polishes them, and most importantly enables them to work with forked repositories and branches instead of just internal ones.
Only pull requests made after this is merged will work with the actions.
> Allow preview actions to work with external branches / repositories

- src/context/intermediate/modals/Onboarding.tsx
Adds a linebreak before the logo on the onboarding modal.
**New:**
**Old:**
> Add linebreak before onboarding logo

- .gitignore
This PR is very simple, adding .idea to gitignore for using webstorm (or an other jetbrains IDE).
> Add .idea on Gitignore

- src/components/common/messaging/embed/EmbedInvite.tsx
- Fixed mobile display issues
- Add line limit for very long server names
- Display join errors below embed
- Keep spinner on button click until server is joined
- Show "member" instead of "members" on invites with only 1 member
(screenshot with devtools mobile web emulator active and invite URLs blocked)
> Invite embed improvements

- src/pages/settings/panes/MyBots.tsx
The fake dots that resemble the bot token can sometimes make the "Reveal" button unavailable, so would be best to remove it altogether
> Shorten bots token dots

- src/lib/ContextMenus.tsx
- fixes `reply` and `quote message` from appearing in the context menus for messages when unable to send messages.
- fixes #265
> Fix send message related context menu options when unable to send messages

- src/context/intermediate/modals/Prompt.tsx
before
after (in conjuction with https://github.com/revoltchat/translations/pull/14)
> [fix] Show "Category Name" instead of "Channel Name" when creating Category

- src/pages/settings/panes/Appearance.tsx
"Theme Shop" link on Appearance won't rewrite browser history. Going in _User Settings > Appearance > Theme Shop >  Appearance > Theme Shop > Appearance > ..._ will put histories in the browser and users will have to click X multiple times to go back to the main page
Before:
After:
> feat: Theme shop link on appearance rewrites history

- src/pages/invite/InviteBot.tsx
"un selected" is grammatically incorrect, and "Select a (type)" gives more context about what to do with the dropdown.
> fix: Correct grammar in bot invite screen

- src/components/common/messaging/Message.tsx
- src/components/common/messaging/attachments/Attachment.tsx
- src/lib/ContextMenus.tsx
When clicking a message with attachments, the context menu items
regarding attachments (save, open, copy link) no longer appear.
When clicking on an attachment in a message with multiple attachments,
the context menu items will be available and actually use the clicked on
attachment, not always the first one.
Closes #337
> fix: add context menu to individual attachments if > 1 attached

- src/pages/settings/panes/Audio.tsx
- src/pages/settings/panes/Panes.module.scss
This PR shows a text and button to access grant permission in audio setting.
Resolves #242, resolves revoltchat/revolt#112
before:
after:
This PR requires revoltchat/translations#10
> feat(settings): prompt for audio access from button

- src/components/common/AutoComplete.tsx
- why? it makes typing `:3` easier
> feat: require at least two characters to autocomplete emoji

- index.html
- src/components/navigation/right/Search.tsx
- src/components/ui/Overline.tsx
Use prop `hoverEnabled` to enable the hover event for an Overline element.
Specifically enabled this for the back to members button in the search panel!
This fixes issue #286.
Fixes #286.
Fixes #343.
> fix: added hover event to overline + removed context menu

- src/pages/settings/panes/Profile.tsx
The toki pona translation of this string only makes sense on the profile
page, and wouldn't make sense if used as an action button. This is to
reduce the chance of the string being used in other contexts.
> chore: rename the string for previewing the profile page

- src/context/intermediate/modals/Prompt.tsx
- src/pages/settings/ServerSettings.tsx
- src/pages/settings/Settings.module.scss
This PR adds a button to the server settings menu to delete said server. This only shows if the user is the server owner.
Currently, while the server is deleted the user is not redirected to the home page. I've tried `history.push("/")` to no avail - any ideas?
> feat: add delete server button to server settings

- src/components/ui/Modal.tsx
There is a race condition between the animation finishing and the modal being removed from the div, meaning that if the animation finishes first, it will return back to the default state. The 'animation-fill-mode: forwards' makes the animation stop at its final stage.
> fix(ui): flicker on modal close

- src/pages/settings/server/Categories.tsx
> fix: make the category name input use --font

- Dockerfile
> fix(docker): fix vite-plugin-pwa failing on build #416

- Dockerfile
- src/components/navigation/SidebarBase.tsx
- src/components/navigation/left/ServerListSidebar.tsx
- src/components/navigation/left/ServerSidebar.tsx
- src/components/ui/Button.tsx
- src/components/ui/Header.tsx
- src/components/ui/Tip.tsx
- src/context/intermediate/popovers/UserProfile.module.scss
- src/pages/RevoltApp.tsx
- src/pages/channels/ChannelHeader.tsx
- src/pages/home/Home.module.scss
- src/pages/settings/Settings.module.scss
- src/pages/settings/Settings.tsx
- src/pages/settings/panes/Account.tsx
- src/pages/settings/panes/Appearance.tsx
- src/pages/settings/panes/Audio.tsx
- src/pages/settings/panes/MyBots.tsx
- src/pages/settings/panes/Panes.module.scss
- src/pages/settings/panes/Profile.tsx
- src/pages/settings/panes/Sync.tsx
- src/pages/settings/panes/ThemeShop.tsx
- src/sw.ts
To-Do list taken from development server:
**Channel header:**
**Server sidebar:**
**Channel window:**
**Profile settings:**
**Voice settings:**
**Appearance:**
**Sync settings:**
**Theme Shop:**
> feat(settings): UI improvements

- src/components/markdown/Renderer.tsx
feat: Add markdown formatting for messages containing timestamps
Closes https://github.com/revoltchat/revite/issues/129
> feat: add markdown formatting for messages containing timestamps

- src/components/markdown/Markdown.module.scss
> fix(components): add padding-right to markdown code element

- src/pages/login/forms/FormLogin.tsx
- src/pages/settings/panes/Sessions.tsx
Currently, iPadOS users are either detected as macOS users or (all iOS users if using Chrome) "Crios". This PR fixes detection for these.
> fix: properly detect ipados

- .github/actions/build/action.yml
- .gitlab-ci.yml
- package.json
- yarn.lock
This PR removes highlight.js, which is completely unused (for those unaware, we use Prism for code highlighting) and takes up install time/space. This PR also updates the CI to use Node 16.
> chore: remove highlight.js, use node 16 for ci

- src/pages/settings/panes/Sessions.tsx
This PR fixes the i(Pad)OS regex to correctly detect iOS. This makes sure the Apple logo is displayed for both iOS and iPadOS.
> fix: fix iOS regex

- src/components/ui/Checkbox.tsx
- src/mobx/stores/Plugins.ts
- src/pages/settings/Settings.tsx
- src/pages/settings/panes/Panes.module.scss
- src/pages/settings/panes/Plugins.tsx
Does what it says on the tin. Note this is heavily WIP, and further PRs will (probably) follow.
However, depending on how the PR is received by whoever reviews it, development of the plugins page can continue here by turning the PR into a draft.
A related PR has been made on the [translation repository](https://github.com/revoltchat/translations/pull/30).
---
(not exactly a screenshot, but I hope this suffices)
https://user-images.githubusercontent.com/54973868/160474001-dd08492e-fe26-464d-ba1d-9e5f72f59063.mp4
> feat: Implement a plugins page

- .github/ISSUE_TEMPLATE/bug.yaml
This commit fixes a typo that has been mentioned in #570.
> Fix a typo

- src/components/common/messaging/embed/Embed.tsx
- src/context/revoltjs/FileUploads.tsx
- src/pages/settings/panes/MyBots.tsx
> fix(components): wrong calculation of dimensions of embeds layouts

- src/components/common/messaging/MessageBox.tsx
- src/components/settings/AppearanceShims.tsx
- src/mobx/stores/Settings.ts
- src/pages/settings/panes/Appearance.tsx
PR to translation repo will follow.
Adds a toggle to display the Send Message button in the message box on Desktop:
> feat: Add option to show Send button on Desktop

- src/components/common/messaging/embed/Embed.module.scss
- src/components/common/messaging/embed/EmbedMedia.tsx
ution guide](https://github.com/revoltchat/revolt/discussions/282)
Fixes #692
> fix: large images in website previews escape embed box

- src/components/markdown/RemarkRenderer.tsx
Fixes #733 
Before:
After:
Actual markdown:
```md
Nothing before:
<h1>**Markdown**
Something Before:
Text<h1>**Markdown**
<h1>**Markdown**
<h1>**Markdown**
```
As pointed out in https://github.com/revoltchat/revite/issues/733#issue-1303498835, if there's text before HTML tag, it would render the markdown. so the code adds an empty character if a line starts with an HTML tag.
This is an alternative to #734
> fix: render markdown inside/after HTML tags

- src/pages/app.tsx
- src/pages/login/forms/Form.tsx
This fixes emoji names that have a `-` in them. For example, this fixes the usage of `:non-potable_water:` to show the emoji properly without avoiding this error by changing all emoji names to not have any `-`'s in them.
Along with fixing this bug, it also removed an unnecessary "one or more" operator in the same `RE_EMOJI` expression. This makes no difference to validating with the expression, except to readability.
before
after
> fix: dash ("-" char) in emoji names

- src/pages/settings/server/Categories.tsx
Fixes #693 
Read more https://github.com/revoltchat/revite/issues/693#issuecomment-1156718105 https://github.com/revoltchat/revite/issues/693#issuecomment-1156735269
Preview:
> fix: category title input reverts to span on empty string

- src/components/common/AutoComplete.tsx
This fixes the `-` character when checking if something in the chat box is valid for auto-correct searching. This fixes `:non-potable_water:` when finding it via auto-correct after entering the `-` character.
Before:
After;
> fix: allow dash char in autocorrect content validation

- src/assets/changelogs.tsx
fix: Usernames are evolving link to blog page(sorry for not following proper format sorta dumb)
> fix: Usernames are evolving blog post link

- src/pages/home/Home.module.scss
this pr fixes inconsonant height in the buttons by making all of them the same size :3
before:
after:
> fix(home): inconsistent discover button height

- src/pages/settings/server/Categories.tsx
This PR fixes a minor issue where using blank names in categories would lead to them being permanently\* stuck as such. 
Blank names are already prohibited, evident from the 400 error you receive if you try creating a category without entering anything in the name field. For some reason though, simple whitespace characters (including U+0020) *are* allowed. When this happens, the category gets stuck with a blank name due to the `<span>` element ending up with a size of 0x0, and since the click handler responsible for allowing the user to rename the category is attached to that same `<span>` element, you can kinda see how it goes wrong.
I realize that a change to the backend to improve handling of whitespace characters *would* be the more ideal solution, but this change on the frontend is …
> fix(settings): fixed inability to rename categories when they have blank names

- src/components/common/messaging/attachments/AttachmentActions.tsx
- src/lib/ContextMenus.tsx
Due to recent changes elsewhere `/download` is no longer needed in attachment URLs. This PR removes it.
> fix: remove /download from attachments

- .github/pull_request_template.md
Hi, in testing for another PR involving the CI I got an error when I tried to create a PR, there is a workflow that tried to run, and so I'm setting it so that it only runs on a repo owned by revoltchat.
I'm likely to file the same PR against revoltchat/frontend as time permits.
~~* [ ] (optional) I have opened a pull request on [the translation repository](https://github.com/revoltchat/translations)~~
~~* [ ] I have included screenshots to demonstrate my changes~~
> chore: tidy up CI

- src/components/common/messaging/attachments/AttachmentActions.tsx
The open button now opens file in browser and download button downloads the file, so things are back in place and not swapped.
←  These do the thing properly now
> fix: correct open/download link behaviour

- src/components/navigation/right/MemberSidebar.tsx
Small fix to add a ViewChannel check when rendering members in the sidebar, just so people on Revite can have a better experience while waiting for Revolt for Web
> fix: filter out members without ViewChannel
